server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tusherbhomik2018@gmail.com
    password: dqzbysyzoibtrpzl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
